### ISSUE TITLE
Roll-20 like dice rolling

### ISSUE THREAD

**Issue by DonaldTsang** [GreenImp/rpg-dice-roller#60]
RPG dice rolling function covering more features
- [x] addition, subtraction, multiplication, division
- [x] modulo, exponentiation
    _Note: with modulus and exponentiation, at present, you need to surround the roll with parenthesis. ie. `(1d6)%2`, `(1d6)^0.5`_ (See #90)
- [x] floor, round, ceil, abs (See #64)
    - >Abilities are expanded (meaning the definition of the ability is placed in the formula anywhere that ability appears).
Macros are expanded, including nested macros up to 99 levels deep.
Variables are substituted
Roll queries are executed (the player making the roll is asked to provide a value for each query, and that value is substituted in where the roll query appears in the formula)
All previous steps are repeated until there are no longer any unresolved abilities, macros, variables, or queries. This allows for nesting (e.g. putting an attribute in a macro).
Inline rolls are executed, starting with the most deeply nested inline roll working upward. The overall result of the inline roll is substituted in place where it appeared in the formula.
The remaining roll is executed: first, dice are rolled for any dice (e.g. "2d6" is rolled; including any special dice such as dropped or exploding), then the result of that roll is substituted into the formula. Next, floor() and ceil() functions are executed. Finally, the entire remaining formula is evaluated, including observing proper math order of operations (parentheses first, then multiplication/division, then addition/subtraction).
- [x] All Types Of Dice
    - [x] Basic Roll of `NdX`
    - [x] Fate/Fudge Roll `NdF`
    - [x] Computed Dice Roll `(N+Y)dX` or `Nd(X+Y)`
- [ ] All Roll Modifiers
    - [x] Target Number / Successes (B,F) - CP
    - [x] Failures (B,F) - fCP
    - [x] Exploding Dice (B,F) !CP
    - [x] Compounding Dice (B,F) !!CP
    - [x] Penetrating Dice (B,F) !pCP
    - [ ] Dice Matching `m` and `mt`
    - [x] Keep / Drop Dice (B,F) `khN` or `klN` or `dhN` `dlN` (See #65)
    - [x] Rerolling Dice (B,F) `rCP` (See #89)
    - [x] Sorting Dice (B,F) `sa` or `sd`
    - [x] Order of Operations for Modifiers
        -  >Exploding, Compounding, Penetrating, Rerolls
These are applied while the dice are still rolling. imagine that you roll some exploding 6d6 on your table and the instant one of them settles as a 6 another die is rolled
Keep, Drop, Success, Failure, Sorting
These are applied after all of the dice have "settled" and all of the result values are known.
- [ ] Grouped Rolls (See #88)
- [ ]  Grouped Roll Modifiers (See #88)
    - [ ] Keep / Drop `khN` or `klN` or `dhN` or `dlN`
    - [ ]  Target Number / Successes (B,F) `CP`
    - [ ] Failures (B,F) `fCP`

Code: https://app.roll20.net/assets/dengine.js?v=123
Mirror: https://ghostbin.com/paste/2n67m
Reference: https://wiki.roll20.net/Dice_Reference

**Comment by GreenImp** [comment]
We already cover a lot of the dice syntax that roll20 does (Excluding things with variables, ie. `2d6+{CHARISMA_MOD}`)

However, I'm always happy to look at new formats. Is there anything in particular that you're after?

Also, just to note that I wouldn't be able to just copy+paste the Roll20 code, as it would be in breach of their copyright. I also think that their dice rolling stuff is actually done server-side, not in the JS anyway - probably to stop people copying the code.

**Comment by GreenImp** [comment]
I'm sorry, but I can't just copy someone else's code.

If there is a particular feature that you're after, that Roll20 has, that I don't, I'll be more than happy to look into the possibility of implementing our own version of it.

**Comment by DonaldTsang** [comment]
@GreenImp I would recommend having a "clean room design" to support such features.
- [ ] addition, subtraction, multiplication, division, modulo, exponentiation
    - >Abilities are expanded (meaning the definition of the ability is placed in the formula anywhere that ability appears).
Macros are expanded, including nested macros up to 99 levels deep.
Variables are substituted
Roll queries are executed (the player making the roll is asked to provide a value for each query, and that value is substituted in where the roll query appears in the formula)
All previous steps are repeated until there are no longer any unresolved abilities, macros, variables, or queries. This allows for nesting (e.g. putting an attribute in a macro).
Inline rolls are executed, starting with the most deeply nested inline roll working upward. The overall result of the inline roll is substituted in place where it appeared in the formula.
The remaining roll is executed: first, dice are rolled for any dice (e.g. "2d6" is rolled; including any special dice such as dropped or exploding), then the result of that roll is substituted into the formula. Next, floor() and ceil() functions are executed. Finally, the entire remaining formula is evaluated, including observing proper math order of operations (parentheses first, then multiplication/division, then addition/subtraction).
- [ ] All Types Of Dice
    - [ ] Basic Roll of `NdX`
    - [ ] Fate/Fudge Roll `NdF`
    - [ ] Computed Dice Roll `(N+Y)dX` or `Nd(X+Y)`
- [ ] All Roll Modifiers
    - [ ] Target Number / Successes (B,F) - CP
    - [ ] Failures (B,F) - fCP
    - [ ] Exploding Dice (B,F) !CP
    - [ ] Compounding Dice (B,F) !!CP
    - [ ] Penetrating Dice (B,F) !pCP
    - [ ] Dice Matching `m` and `mt`
    - [ ] Keep / Drop Dice (B,F) `khN` or `klN` or `dhN` `dlN`
    - [ ] Rerolling Dice (B,F) `rCP`
    - [ ] Sorting Dice (B,F) `sa` or `sd`
    - [ ] Order of Operations for Modifiers
        -  >Exploding, Compounding, Penetrating, Rerolls
These are applied while the dice are still rolling. imagine that you roll some exploding 6d6 on your table and the instant one of them settles as a 6 another die is rolled
Keep, Drop, Success, Failure, Sorting
These are applied after all of the dice have "settled" and all of the result values are known.
- [ ] Grouped Rolls
- [ ]  Grouped Roll Modifiers
    - [ ] Keep / Drop `khN` or `klN` or `dhN` or `dlN`
    - [ ]  Target Number / Successes (B,F) `CP`
    - [ ] Failures (B,F) `fCP`

**Comment by DonaldTsang** [comment]
https://github.com/mog13/DXJS

**Comment by GreenImp** [comment]
I have ticked the features in your comment above that we have already covered fully.

- _Addition, subtraction, multiplication_, and _division_ are already built in, but _modulo_, and _exponentiation_ are not.
I'm not sure of the use case for them in dice-based games either. If there is a big need for them, then I can add a task for looking into it.
- _Floor, round, ceil, abs_ I can see a good use for something like this, although at present we only ever deal with whole numbers as decimal points are ignored. This arguably needs to be changed.
  - [ ] Create task for allowing decimal points in numbers
  - [ ] Create task for looking into Floor/Round/Ceil/Abs
- _All Types Of Dice_
  - _Computed Dice Roll `(N+Y)dX` or `Nd(X+Y)`_ Are you wanting template variable parsing like `({n1} + {n2})d{n3}`?
This is really out of scope for this dice roller at the moment. However, you can easily build up a string like that yourself in plain JS, with template literals:
    ```javascript
    const diceRoller = new DiceRoller(),
          n = 2,
          y = 3,
          x = 6;

    diceRoller.roll(`${n + y}d${x}`);
    ```
- _All Roll Modifiers_
  - _Dice Matching `m` and `mt`_ I'm not certain what this is?
  - _Keep / Drop Dice_ This is worth looking into.
    - [ ] Create task for Keeping/Dropping number of dice (High or Low)
  - _Rerolling Dice_ I'm not sure what you're wanting to re-roll and how it would differ from compounding/exploding/penetrating dice? Or is it more like what is raised in #2?
  - _Sorting Dice_ I'm not sure what this is. If it's sorting the rolled values ascending/descending, I'm not sure of a use case, and it could cause conflicts with things like compounding dice.
  - _Order of Operations for Modifiers_ There is already a task open for this: #34
- _Grouped Rolls_ Is this the same as #14?

**Comment by GreenImp** [comment]
Closing as seperate issues have been created.

**Comment by DonaldTsang** [comment]
@GreenImp 

- Reroll: `Several systems require that certain dice be reroll, for example brutal weapons in D&D 4e require any 1s or 2s to be re-rolled and the original die value ignored. The reroll modifier can be specified multiple times to allow rerolling at multiple Compare Points. By default the dice will continue to reroll until the result is inside the defined parameters. Optionally you can set the results to only reroll once regardless of the outcome.`
- Sorting: `You may want to see your results in either ascending or descending order. The sorting modifier does just this. The order parameter is optional and specifies the order to sort with a for ascending and d for descending. Sorting defaults to ascending if order is not specified.`
- Dice Matching: `It is possible to show how many of the dice rolled result in matches in the chat window. This feature works with the chat dice as well as the 3d dice, but the matches are only shown in the chat output. m will show matches visually but not change results of the roll. mt will return the number of matches, regardless of the number of dice that match.`

**Comment by GreenImp** [comment]
Cheers for the update.
* _Reroll:_ that sounds handy. Similar to penetrating dice, but where previous rolls are ignored?
    Do you have any thoughts on what the notation would look like for this? What do Roll20 do here?
* _Sorting:_ When you say sorting results, do you mean the individual rolls? So sorting ascending would make this:
    ```
    3d6: [5, 2, 4] = 7
    ```
    Become this?:
    ```
    3d6: [2, 4, 5] = 7
    ```
* _Dice Matching:_ I'm still not entirely clear what you mean here. What do you mean by a "match"? Are you referring to [DIce Pools](https://github.com/GreenImp/rpg-dice-roller/tree/master#dice-pools)?

**Comment by DonaldTsang** [comment]
@GreenImp I might need to read the documentation again to see what they mean.

**Comment by DonaldTsang** [comment]
Moved the information to the description @GreenImp 
Question:
1. Does `floor(), round(), ceil(), abs()` exist? 
2. Does basic mathematic operators exist?
3. Does the keep/drop/reroll operators exist?
P.S. the description's check box can be edited by you, so you can check it out again if you have time.

**Comment by GreenImp** [comment]
1. Yes `floor()`, `round()`, `ceil()`, and `abs()` exist, and are in the documentation (See #64)
2. You mean like addition, subtraction, and division? Yes they're implemented
3. Keep/Drop is not implemented, but there's an open task for it: #65
Re-rolling is not implemented either. I've just created a task for it: #89

**Comment by GreenImp** [comment]
* **Computed Dice Roll `(N+Y)dX` or `Nd(X+Y)`** - What would a use case be for this?
* **Dice Matching `m` and `mt`** - This seems to be for visually differentiating things by colour in the Roll20 roll output? This library doesn't have a GUI or coloured output, so not sure that it's relevant?
* **Sorting Dice (B,F) `sa` or `sd`** - I've found this in the Roll20 docs. As I said before, I'm not sure of a use case for it, and it could cause conflicts with how things like exploding/compounding dice are calculated. If it's really wanted then I'll look into it.

If I can get feedback on that, I can look into getting separate issues raised for them to make it easier to track.

**Comment by GreenImp** [comment]
I'm going to close this ticket now. Everything has either been implemented in the re-write and will go out as v4.0.0, or has an open ticket specific to that item.

The grouped rolls and modifiers are covered by ticket #88.

The only one that isn't is the Dice Matching `m` and `mt`. After reading the Roll20 docs, I'm unsure eaxactly what this does and it seems to be very much relating to how it colours things visually on there. It seems out of scope for this at present, as we're only dealing with plain text output.
